qisimah/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\FileController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

# Landing Page
Route::get('welcome', 'HomeController@landing')->name('welcome');
Route::get('about-us', 'HomeController@about');
Route::get('contact-us', 'HomeController@contact');
Route::get('log-in', 'HomeController@login');

Route::get('logout', function (){
    Auth::logout();
    return redirect()->to('log-in');
});

# Pusher
Route::post('/pusher/auth', 'UserController@authPusherSubscription');

Route::post('/user/{id}/update', 'UserController@update');

Route::get('charts', function(){
    return view('auth.charts');
});

Route::get('chart', function(){
    return view('auth.charts');
});

Route::get('profile', 'ArtistController@profile');

Route::get('chart/top7', 'ChartController@top7');
Route::get('chart/top24', 'ChartController@top24');
Route::get('chart/top30', 'ChartController@top30');
Route::get('halloffame', function(){
    return view('auth.halloffame');
});

Route::get('report/summary', 'ReportController@month');
Route::get('report/monthly', 'ReportController@getMonthlyReport');
Route::get('report/plays/{file_id}/{start}/{end}', 'ReportController@content');
Route::get('report/heat-map/{file_id}/{start}/{end}', 'ReportController@heatMap');
Route::post('report/content', 'ReportController@fetchContentPlays');

Auth::routes();
Route::get('/', 'UserController@index');

Route::post('uploads/song', 'FileController@uploadSong');
Route::get('uploads/song', 'FileController@create');
Route::get('uploads/song/{file_id}/metadata', 'FileController@metadata');
Route::put('songs/{id}', 'FileController@update');
Route::get('file/create/{type}', 'FileController@create');
Route::get('file/{id}/details', 'FileController@details');

Route::post('songs/metadata', 'FileController@saveMetadata');
Route::get('songs', 'FileController@index');

Route::post('/file/create/{type}', function ($type, Request $request){
    return FileController::store($type, $request);
});

Route::get('plays/regions/{country_id}/{file_id}/{start}/{end}', 'RegionController@index');
Route::resource('file', 'FileController');
Route::get('/country/region/{country_id}', 'CountryController@countryRegions');
Route::resource('country', 'CountryController');
Route::get('/tag', 'TagController@index');
Route::get('/play/today', 'PlayController@playsToday');
Route::get('/play/count/today', 'PlayController@getTodayPlayCount');
Route::get('/updates', 'PlayController@getRealTimeUpdates');
Route::get('/play/broadcaster', 'PlayController@playsOfBroadcaster');
Route::get('/play/broadcaster/{stream_id}/{start}/{end}', 'PlayController@getBroadcasterPlays');
Route::get('/play/content', 'PlayController@playsOfContent');
Route::get('/play/artist/{id?}', 'PlayController@getArtistSongs');
Route::get('/play/content/{id}/{start}/{end}', 'PlayController@getContentPlays');
Route::post('/plays', function (Request $request){
    return redirect("/plays/".$request->input('start_date', date('Y-m-d'))
        ."/"
        .$request->input('end_date', date('Y-m-d')));
});

Route::get('/plays/{start}/{end}', 'PlayController@getPlays');
Route::post('/file/create/{type}', function ($type, Request $request){
    return FileController::store($type, $request);
});

Route::post('uploads/song', 'FileController@uploadSong');

Route::resource('file', 'FileController');
Route::get('/play/today', 'PlayController@playsToday');
Route::get('/play/broadcaster', 'PlayController@playsOfBroadcaster');
Route::get('/play/broadcaster/{stream_id}/{date}', 'PlayController@getPlaysOfBroadcaster');
Route::get('/play/content/{detection_id}/{date}', 'PlayController@getPlaysOfContent');
Route::get('/play/{day}', 'PlayController@getPlays');
Route::get('/admin/create', 'AdminController@create');
Route::get('/account/verify/{token}', 'AdminController@verify');
Route::get('/account/password/create', 'AdminController@createPassword');
Route::post('/account/password/create', 'AdminController@updatePassword');
Route::post('/detection', 'PlayController@store');
Route::resource('play', 'PlayController');
Route::get('/broadcaster/select', 'BroadcasterController@select');
Route::resource('broadcaster', 'BroadcasterController');
Route::resource('share', 'ShareController');
Route::resource('subscribe', 'SubscribeController');
Route::resource('pay', 'PayController');
Route::resource('admin', 'AdminController');
Route::resource('artist', 'ArtistController');
Route::resource('albums', 'AlbumController');
Route::resource('play', 'PlayController');
Route::resource('file', 'FileController');
Route::resource('contact', 'ContactController');
Route::resource('contact', 'ContactController');
Route::resource('producer', 'ProducerController');
Route::resource('labels', 'LabelController');
Route::resource('country', 'CountryController');
Route::get('/home', 'HomeController@index');
Route::post('/listen', 'ListenController@store');
Route::post('/listen/delete', 'ListenController@destroy');
Route::resource('contact', 'ContactController');
Route::get('/producer/{id}', 'ProducerController@show');
Route::resource('contact', 'ContactController');
Route::resource('producer', 'ProducerController');

// Genres
Route::get('/genre', 'GenreController@index');
Route::get('/genre/{id}', 'GenreController@show');
Route::post('/genre/create', 'GenreController@store');
Route::post('/genre/create', 'GenreController@store');

qisimah/resources/views/pages/album-index.blade.php
@extends('layouts.master')
@section('title')
    Albums <a href="{{ route('albums.create') }}" class="btn btn-black btn-outline">add new album</a>
@endsection
@section('content')
    <br>
    @if(session('success'))
        <div class="alert alert-success col-sm-10 col-sm-offset-1">
            <p class="text-center">
                {{ session('success') }}
            </p>
        </div>
    @elseif(session('error'))
        <div class="alert alert-danger col-sm-10 col-sm-offset-1">
            <p class="text-center">
                {{ session('error') }}
            </p>
        </div>
    @endif
    <div class="row">
        @if($albums->count() === 0)
            <div class="col-sm-12">
                <p class="text-center"> There are no albums at the moment!</p>
            </div>
        @else
            @foreach($albums as $album)
                <div class="media-left col-xs-12 col-md-3">
                    <div class="widget">
                        <div style="height: 100px" class="overlay-container overlay-color"><img
                                    src="{{asset($album->img)}}" alt="" class="overlay-bg img-responsive">
                        </div>
                        <div style="position: relative"><a href="#"
                                                           style="position: absolute; top: -70px; left: 50%; margin-left: -50px; border-radius: 50%; padding: 3px; background-color: #FFF"><img
                                        src="{{asset($album->img)}}" width="100" alt=""
                                        class="img-circle"></a></div>
                        <div class="text-center p-20 bd-l bd-r">
                            <h4 class="widget-title mt-30 mb-5">{{ $album->name }}</h4>
                            <p>{{ $album->artist->nick_name ?? 'Qisimah' }} / {{ $album->release_date }}</p>
                        </div>
                        <div class="row row-0 p-15 text-center bg-black">
                            <div class="col-xs-4" style="margin-top: 8px">
                                <form action="{{ route('albums.destroy', $album) }}" method="post">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-danger btn-outline delete-album">
                                        <i class="ti-trash fs-30"></i>
                                    </button>
                                </form>
                            </div>
                            <div class="col-xs-4">
                                <div class="fs-20 fw-500">{{ $album->files->count() }}</div>
                                <div class="text-muted">Tracks</div>
                            </div>
                            <div class="col-xs-4" style="margin-top: 8px">
                                <a href="{{ route('albums.edit', $album) }}" class="btn btn-primary
                                btn-outline">
                                    <i class="ti-pencil fs-30"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif
    </div>
@endsection

qisimah/resources/views/pages/createuser.blade.php
@extends('layouts.master')@section('title')    Users@endsection@section('content')    <div class="page-content container-fluid">        <div class="row">            @if(session('success'))                <div class="alert alert-success text-center">                    {{ session('success') }}                </div>            @elseif(session('failed'))                <div class="alert alert-danger text-center">                    {{ session('failed') }}                </div>            @elseif($errors->any())                @foreach($errors->all() as $error)                    <div class="alert alert-danger text-center">                        {{ $error }}                    </div>                @endforeach            @endif            <div class="col-xs-12 col-md-10 col-md-offset-1">                <div class="widget">                    <div class="widget-heading">                        <h3 class="widget-title">add new user</h3>                    </div>                    <div class="widget-body">                        {!! Form::open(['route' => 'admin.store']) !!}                        @include('components.userform')                        {!! Form::close() !!}                    </div>                </div>            </div>        </div>    </div>@endsection

qisimah/resources/views/pages/index.blade.php
@extends('layouts.master')

@section('title')

    Dashboard

@endsection

@section('content')

<div class="page-content container-fluid">

    <!--Dashboard Cards-->

    <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">

            <div class="widget no-border overlay-container">

                <img src="{{asset('images/backgrounds/03.jpg')}}" alt="" class="overlay-bg img-responsive">

                <div class="overlay-content p-10">

                    <div class="clearfix">

                        <div class="pull-left">

                        <!--<img src="{{asset('images/users/Kofi-Kinaata-Susuka-Cover-artwork.jpg')}}" alt="" width="100" class="media-object img-thumbnail">-->

                            <i class="fs-60 zmdi zmdi-play-circle-outline"></i>

                            <div class="mt-15 mb-5 fw-500 fs-17">{{date('l')}}</div>

                            <div class="fs-15">{{\Carbon\Carbon::today()->toDateString()}}</div>

                        </div>

                        <div class="pull-right text-right">

                            <div class="fs-17">

                                <strong>Plays Today</strong>

                            </div>

                            <div class="fs-45 fw-700">

                                <span id="today-plays" class="counter">0</span>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>



        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">

            <div class="widget no-border overlay-container">

                <img src="{{asset('images/backgrounds/music.jpg')}}" alt="" class="overlay-bg img-responsive">

                <div class="overlay-content p-10">

                    <div class="clearfix">

                        <div class="pull-left">

                            <i class="fs-60 zmdi zmdi-trending-up"></i>

                        <!--<img src="{{asset('images/users/Kofi-Kinaata-Susuka-Cover-artwork.jpg')}}" alt="" width="65" width="65" class="media-object img-thumbnail">-->

                            <div class="mt-15 mb-5 fw-500 fs-17">

                                <strong id="most-played-title">Title</strong>

                            </div>

                            <div id="most-played-artist" class="fs-15">Artist</div>

                        </div>

                        <div class="pull-right text-right">

                            <div class="fs-17">

                                <strong>Most Played</strong>

                            </div>

                            <div class="fs-45 fw-700">

                                <span id="most-played" class="counter">0</span>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>



        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">

            <div class="widget no-border overlay-container">

                <img src="{{asset('images/backgrounds/23.jpg')}}" alt="" class="overlay-bg img-responsive">

                <div class="overlay-content p-10">

                    <div class="clearfix">

                        <div class="pull-left">

                            <i class="fs-60 zmdi zmdi-star-circle"></i>

                        <!--<img src="{{asset('images/users/Kofi-Kinaata-Confession.jpg')}}" alt="" width="26%" height="26%" class="media-object img-thumbnail">-->

                            <div class="mt-15 mb-5 fw-500 fs-17">

                                <strong id="all-time-title">title</strong>

                            </div>

                            <div id="all-time-artist" class="fs-15">artist</div>

                        </div>

                        <div class="pull-right text-right">

                            <div class="fs-17">

                                <strong>All time best</strong>

                            </div>

                            <div class="fs-45 fw-700">

                                <span id="all-time-play" class="counter">0</span>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>



        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">

            <div class="widget no-border overlay-container">

                <img src="{{asset('images/backgrounds/36.jpg')}}" alt="" class="overlay-bg img-responsive">

                <div class="overlay-content p-10">

                    <div class="clearfix">

                        <div class="pull-left">

                            <i class="fs-60 zmdi zmdi-mic-outline"></i>

                        <!--<img src="{{asset('images/users/live fm.png')}}" alt="" width="65" height="65" class="media-object img-thumbnail">-->

                            <div class="mt-15 mb-5 fw-700 fs-17">

                                <strong id="broadcaster-name">name</strong>

                            </div>

                            <div class="fs-15" id="broadcaster-country">country</div>

                        </div>

                        <div class="pull-right text-right">

                            <div class="fs-17">

                                <strong id="">Broadcaster</strong>

                            </div>

                            <div class="fs-45 fw-700"><span class="counter" id="broadcaster-plays">0</span></div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

    <!--Dashboard Cards-->

    <!--plays table-->

    <!--END plays table-->

    <div class="row">
        <div class="col-lg-12">
            <div class="widget clear">
                <div class="widget-heading clearfix">
                    <h3 class="widget-title text-center">Live Detections</h3>
                </div>
                <div class="widget-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="widget no-border">
                                <table id="live-detection" style="width: 100%"
                                       class="table table-hover table-bordered">
                                    <thead>
                                    <tr>
                                        <th style="width:35%" class="">Song</th>
                                        <th style="width:30%" class="">Broadcaster</th>
                                        <th style="width:15%" class="text-center">Time Played</th>
                                        <th style="width:10%" class="text-right">Plays Today</th>
                                        <th style="width:10%" class="text-right">This Week</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

qisimah/resources/views/pages/selectbroadcaster.blade.php
@extends('layouts.master')
@section('title')
    Select Broadcasters
@endsection
@section('content')
    <div class="page-content container-fluid">
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="widget row p-20">
                    <div class="widget-body form-group">
                        <select class="form-control col-lg-6" id="searchable-ms" multiple="multiple">
                            <option value="Y FM">Y FM</option>
                            <option value="CSS">Peace FM</option>
                            <option value="Javascript">Live FM</option>
                            <option value="PHP">Joy FM</option>
                            <option value="ASP.NET">Adom FM</option>
                            <option value="Visual Basic">Metro FM</option>
                            <option value="Java">Luv FM</option>
                            <option value="Python">Happy FM</option>
                            <option value="Less">Star FM</option>
                            <option value="Stylus">Radio Gold</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="text-right">
                            <button type="submit" class="mt-15 btn btn-primary"><i class="ti-plus mr-5"></i>Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

qisimah/resources/views/pages/updatebroadcaster.blade.php
@extends('layouts.master')@section('title')    Edit Broadcaster@endsection@section('content')    <div class="page-content container-fluid">        <div class="row">            <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">                <div class="widget">                    <div class="widget-heading">                        <h3 class="widget-title">Editing {{ $broadcaster->name }}</h3>                    </div>                    <div class="widget-body">                        {!! Form::model( $broadcaster, ['route' => ['broadcaster.update', $broadcaster], 'files' => true, 'method' => 'PUT']) !!}                        @include('components.broadcasterform')                        <div class="col-md-6">                            <div class="form-group">                                {!! Form::label('phone', 'Phone:') !!}                                {!! Form::text('phone', null, ['class' => 'form-control']) !!}                            </div>                        </div>                        <div class="col-xs-12 col-md-6">                            <div class="form-group">                                {!! Form::label('img', 'Select Image File') !!}                                {!! Form::file('img', null, ['class' => 'filestyle', 'data-buttonname' => 'btn-outline btn-primary', 'data-iconname' => 'ti-zip']) !!}                            </div>                        </div>                    </div>                    <div class="text-right">                        {!! Form::submit('Submit', ['class' => 'btn btn-primary btn-outline']) !!}                    </div>                    {!! Form::close() !!}                </div>            </div>        </div>    </div>@stop